feature: create home page with all trainings, hide navigation buttons…
agileactors/training-creator-tool pull request #35
Opened 2023-01-22 18:47 UTC by thTs0ustas

… and side bar

Co-authored-by: Athanasios Tsoustas <thTs0ustas@users.noreply.github.com>

2023-01-23 14:49 UTC, xristos1994 requested changes

2023-01-23 14:49 UTC, xristos1994 commented on gatsby-node.js
> +  const availableTrainingsQuery = await graphql(`
This graphql query is taking place for all trainings and not only for the admin. 
In order to make it only in the admin build, you could move it in the `else` statement a few lines below.

2023-01-23 14:49 UTC, xristos1994 commented on gatsby-node.js
> +            frontmatter {
You could also query for the `title` field in order to use it instead of `${_.upperFirst(trainings?.node?.frontmatter?.uniqueName)}` without having to uppercase the first letter. The title will appear in the format that user added it in the CMS.

2023-01-23 14:49 UTC, xristos1994 commented on gatsby-node.js
> +        body:
Instead of creating a body using markdown, you could just pass the data of all the available trainings and use them in a new page type. 
Please check how the homepage is implemented.

2023-01-23 17:37 UTC, thTs0ustas commented on gatsby-node.js
> +  const availableTrainingsQuery = await graphql(`
Done!

2023-01-23 17:37 UTC, thTs0ustas commented on gatsby-node.js
> +            frontmatter {
Done!

2023-01-23 17:39 UTC, thTs0ustas commented on gatsby-node.js
> +        body:
We created a new Component following the homepage implementation. Let as know if everything is ok.

2023-01-24 08:57 UTC, xristos1994 requested changes

2023-01-24 08:57 UTC, xristos1994 commented on gatsby-node.js
> +                title
You also need the uniqueName because there is no connection between these two fields.
For example, it is possible to create a training with uniqueName `javascript` and title `My Javascript`.

2023-01-24 08:57 UTC, xristos1994 commented on gatsby-node.js
> +    const listOfTrainings = availableTrainingsQuery?.data?.allMarkdownRemark?.edges;
it would be preferable the list of trainings to be an array of objects 
```
{
   title: string,
   url: string
}
```
and ordered alphabetically with title.

2023-01-24 08:57 UTC, xristos1994 commented on gatsby-node.js
> +        body: listOfTrainings,
Instead of `body` you could use 
```
data: {
   listOfTrainings: listOfTrainings
}
```

2023-01-24 08:57 UTC, xristos1994 commented on src/components/AvailableTrainings/AvailableTrainings.jsx
> +                  target="_blank"
I think it would be better to open the Url in the same tab. Because it is something like a table of content.

2023-01-24 08:57 UTC, xristos1994 commented on src/components/AvailableTrainings/AvailableTrainings.jsx
> +  const title = props.title || 'Training';
The default value should be `Trainings` and not `Training`.

2023-01-24 11:27 UTC, xristos1994 requested changes

2023-01-24 11:27 UTC, xristos1994 commented on src/components/TrainingPage/TrainingPage.jsx
> +          {currentPageIndex !== -1 && (
You can add this condition two lines above and have
`mode === 'live && currentPageIndex !== -1`
But I would personally suggest to create a function inside the `TrainingPage` component.
This function should be something like
```
const shouldDisplayNavigationButtons() {
   return true or false depending on conditions
}
```

but in this function you should check the mode and the type and not the currentPageIndex.

2023-01-24 11:29 UTC, thTs0ustas commented on gatsby-node.js
> +                title
Done!

2023-01-24 11:30 UTC, thTs0ustas commented on gatsby-node.js
> +    const listOfTrainings = availableTrainingsQuery?.data?.allMarkdownRemark?.edges;
Done!

2023-01-24 11:30 UTC, thTs0ustas commented on gatsby-node.js
> +        body: listOfTrainings,
Done!

2023-01-24 11:30 UTC, thTs0ustas commented on src/components/AvailableTrainings/AvailableTrainings.jsx
> +                  target="_blank"
Done!

2023-01-24 11:30 UTC, thTs0ustas commented on src/components/TrainingPage/TrainingPage.jsx
> +          {currentPageIndex !== -1 && (
Done!

2023-01-24 11:30 UTC, xristos1994 requested changes

2023-01-24 11:30 UTC, xristos1994 commented on gatsby-node.js
> +    const listOfTrainings = availableTrainingsQuery?.data?.allMarkdownRemark?.edges.reduce(
Why reduce and not just a map?

2023-01-24 11:35 UTC, xristos1994 commented on src/components/TrainingPage/TrainingPage.jsx
> +      return <AvailableTrainings {...props} />;
I think it would make more sense if it was 
`return <AvailableTrainings {...data} title={title} />;`
and use it accordingly in `AvailableTrainings` component

2023-01-24 14:05 UTC, thTs0ustas commented on src/components/TrainingPage/TrainingPage.jsx
> +          {currentPageIndex !== -1 && (
The Page component gives the feeling that there is a box surrounding the footer, and I'd like to keep that even when there are no navigation buttons. That's why I don't add the condition there. Additionally, by checking the current index, we have the ability to dynamically display the navigation buttons regardless of other conditions. I'm not sure what else it offers to check the mode and type instead.

2023-01-24 14:07 UTC, thTs0ustas commented on gatsby-node.js
> +    const listOfTrainings = availableTrainingsQuery?.data?.allMarkdownRemark?.edges.reduce(
Ok!

2023-01-24 14:08 UTC, thTs0ustas commented on src/components/TrainingPage/TrainingPage.jsx
> +      return <AvailableTrainings {...props} />;
Done!

2023-01-24 15:18 UTC, xristos1994 approved these changes

2023-01-24 15:20 UTC, merged